# Generated by Django 3.2.4 on 2021-08-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=75)),
                ('ciudad', models.CharField(max_length=75)),
                ('rfc', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('contacto', models.CharField(max_length=75)),
                ('numero', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_corral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Corral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corral', models.CharField(max_length=75)),
                ('cliente', models.CharField(max_length=75)),
                ('tipoStatus', models.CharField(max_length=75)),
                ('fecha', models.DateField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=75)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=75)),
                ('ciudad', models.CharField(max_length=75)),
                ('rfc', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('contacto', models.CharField(max_length=75)),
                ('numero', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='surtible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=75)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.status')),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=75)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.cliente_corral')),
                ('corral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.corral', verbose_name='Selecciona el corral')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.producto', verbose_name='Selecciona el producto')),
            ],
            options={
                'db_table': 'datos_registro',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='apto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.surtible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.status'),
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.status')),
            ],
        ),
        migrations.CreateModel(
            name='Materia_prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=75)),
                ('precio_unitario', models.BigIntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.status')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Contenedores_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claves', models.CharField(max_length=75, verbose_name='CLAVE')),
                ('capacidad', models.BigIntegerField(verbose_name='CAPACIDAD')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.status', verbose_name='ESTADO')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.provedor', verbose_name='PROVEDOR')),
            ],
        ),
        migrations.CreateModel(
            name='Contenedores_Mat_prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=75, verbose_name='CLAVE')),
                ('capacidad', models.BigIntegerField(verbose_name='CAPACIDAD')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.cliente', verbose_name='CLIENTE')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.status', verbose_name='ESTADO')),
            ],
        ),
    ]
